#!/bin/bash
#===============================================================================
#
#          FILE: wifi-lan
# 
#   DESCRIPTION: Network Manager
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: DANIEL B. BRUMAZZI (Brumazzi), brumazzi_daniel@yahoo.com.br
#  ORGANIZATION: 
#       CREATED: 12-02-2016 13:03
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

. /usr/share/wifi-lan/functions.sh

dev=$(ip addr | grep wlan0)
[[ "$dev" ]] &&
	dev="wlan0" ||
	dev=$(ip addr | grep wlp3s0)
[[ "$dev" ]] &&
	dev="wlp3s0" ||
	exit 1

ifconfig $dev up || exit 2

check(){
	while [ 1 ]; do
		ip=$(ifconfig $dev | grep inet)
		[[ "$ip" ]] ||
			reconnect $dev
		sleep 5
	done
}
